<?php

return [
    'HCAPTCHA_SITE_KEY' => env('HCAPTCHA_SITE_KEY', '6LcUwPwqAAAAAHi5PIoCo1e4pKnbUlw9GIYXy1IS'),
    'HCAPTCHA_SECRET_KEY' => env('HCAPTCHA_SECRET_KEY', '6LcUwPwqAAAAANlCiw4fLINDFDE5EUeb-TCvITGz'),
];
